### ISSUE TITLE
output dir

### ISSUE THREAD

**Issue by FMassin** [SeismicSource/sourcespec#43] opened 2023-07-19 10:57 UTC
Hello

Apparently, the option to write outputs in a specific directory removes the first char of the path, e.g. ~/42 writes in 42 ? It is quite problematic in case something like ~/output is provided because that creates all the subdirs in the current folder !

Cheers

Fred

**Comment by claudiodsf** [comment] 2023-07-19 12:03
Hi Fred,

This might be related to a fix introduced in #40. 

I'm on summer break and I can check this after August 16. 

Feel free to investigate, in the meantime 😉

**Comment by claudiodsf** [comment] 2023-07-19 12:41
Here's the commit: https://github.com/SeismicSource/sourcespec/commit/7ca44542103a6b2f040b4c533637efe472c4346a

**Comment by krisvanneste** [comment] 2023-07-21 11:00
I verified that this issue is not due to the recent commit.
The problem is that the path '~/output' first needs to be converted into an absolute path, before running `makedirs`, otherwise it creates a '~' subfolder in the current folder...

@FMassin until the bug is fixed, could you try using an absolute path?

@claudiodsf I think it should be easy to fix this by calling `os.path.expanduser` if the outputdir starts with '~'. This probably also works in Windows.

**Comment by FMassin** [comment] 2023-07-21 11:17
Sure.

**Comment by FMassin** [comment] 2023-07-21 11:18
> @FMassin until the bug is fixed, could you try using an absolute path?

Sure.

**Comment by krisvanneste** [comment] 2023-07-25 14:33
@claudiodsf I created a new branch `allow_outdir_tilde_expansion` for this feature. While doing this, I realized there are a number of other variables in options and config that contain a path and they are now checked in the same way as `outdir`. It works on my side, but I'm not using most of these options. Could you have a quick look at it to see if this is OK? If not, I could ask the OP to pull this branch and test it.

**Comment by claudiodsf** [comment] 2023-07-26 06:39
Thanks Kris! 

I'll check it out when coming back from summer break, on August 16.

@FMassin, feel free to test Kris' branch 😉

**Comment by claudiodsf** [comment] 2023-08-17 07:18
Link to the relevant pull request, for future reference: #44

**Comment by claudiodsf** [comment] 2023-08-17 07:26
The pull request is merged now (thanks Kris 😄).

@FMassin, can you confirm that this is fixed for you?

**Comment by claudiodsf** [comment] 2023-10-31 16:20
Closing. @FMassin feel free to reopen in case you still have problems.

**Closed by claudiodsf** 2023-10-31 16:20 UTC

**Comment by FMassin** [comment] 2023-10-31 21:51
Sorry yes it was ...
